"""Rule refinement helpers, models, prompts, and iterative extraction service."""

from .artifacts import (
    apply_rule_update_suggestions,
    canonical_rules_base_path,
    iteration_narrative_critique_path,
    lines_to_markdown,
    next_rules_version,
    render_focused_diff,
    render_narrative_critique_markdown,
    save_narrative_critique_artifact,
    save_narrative_suggestion_artifact,
    versioned_diff_path,
    versioned_narrative_suggestion_path,
    versioned_rules_path,
)
from .extractors import (
    DemoBuildRulesLines,
    extract_all_skills,
    extract_global_rules,
    extract_phase_models,
    extract_phase_prompts,
    extract_refinement_inputs,
    extract_skill_content,
    load_demo_build_rules_lines,
)
from .models import (
    ExtractedPrinciples,
    NarrativeCritique,
    NarrativeTuningIterationResult,
    NarrativeTuningPassResult,
    RefinementSource,
    RuleLineReplacement,
    RuleRefinementCallMetrics,
    RuleRefinementIterationArtifact,
    RuleRefinementIterationResult,
    RuleRefinementRunResult,
    RuleRefinementSourceResult,
    RuleUpdateSuggestions,
)
from .prompts import (
    build_narrative_critique_developer_prompt,
    build_narrative_critique_user_prompt,
    build_narrative_improvement_developer_prompt,
    build_narrative_improvement_user_prompt,
    build_principle_extraction_developer_prompt,
    build_principle_extraction_user_prompt,
    build_rule_consolidation_developer_prompt,
    build_rule_consolidation_user_prompt,
    build_rule_update_developer_prompt,
    build_rule_update_user_prompt,
    build_rule_update_user_prompt_for_section,
)
from .sections import split_rules_into_sections
from .service import RuleRefinementService, build_rule_refinement_service

__all__ = [
    "DemoBuildRulesLines",
    "ExtractedPrinciples",
    "NarrativeCritique",
    "NarrativeTuningIterationResult",
    "NarrativeTuningPassResult",
    "RefinementSource",
    "RuleLineReplacement",
    "RuleRefinementCallMetrics",
    "RuleRefinementIterationArtifact",
    "RuleRefinementIterationResult",
    "RuleRefinementRunResult",
    "RuleRefinementService",
    "RuleRefinementSourceResult",
    "RuleUpdateSuggestions",
    "apply_rule_update_suggestions",
    "build_narrative_critique_developer_prompt",
    "build_narrative_critique_user_prompt",
    "build_narrative_improvement_developer_prompt",
    "build_narrative_improvement_user_prompt",
    "build_principle_extraction_developer_prompt",
    "build_principle_extraction_user_prompt",
    "build_rule_consolidation_developer_prompt",
    "build_rule_consolidation_user_prompt",
    "build_rule_refinement_service",
    "build_rule_update_developer_prompt",
    "build_rule_update_user_prompt",
    "build_rule_update_user_prompt_for_section",
    "canonical_rules_base_path",
    "extract_all_skills",
    "extract_global_rules",
    "extract_phase_models",
    "extract_phase_prompts",
    "extract_refinement_inputs",
    "extract_skill_content",
    "iteration_narrative_critique_path",
    "lines_to_markdown",
    "load_demo_build_rules_lines",
    "next_rules_version",
    "render_focused_diff",
    "render_narrative_critique_markdown",
    "save_narrative_critique_artifact",
    "save_narrative_suggestion_artifact",
    "split_rules_into_sections",
    "versioned_diff_path",
    "versioned_narrative_suggestion_path",
    "versioned_rules_path",
]
